### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JeanPaul85** [mskg/homey-fujitsu#1]
Good day,

I tried to install your app on my Homey but got the following errors. 
Could you perhaps help me how to solve this?
![airstage](https://github.com/mskg/homey-fujitsu/assets/54777103/4a186463-2072-4640-b0e5-441f9a1e01cc)

**Comment by mskg** [comment]
I have a look. Most likely the definitions of the Homey API changed while this was developed. It was done during the very early beta of the current Homey PRO. 

It still runs on my side - so can't be a lot.

**Comment by nextlevel2023** [comment]
Hi mskg - this is brilliant, will you update to support the latest Homey API?

**Comment by mskg** [comment]
Done. I published the App, so you can download it probably later this month.
