### ISSUE TITLE
Can't deploy?

### ISSUE THREAD

**Issue by nextlevel2023** [mskg/homey-fujitsu#2]
Hi Markus

I get this when trying to deploy:

test@Pauls-MacBook-Pro com.company.myapp % sudo homey app run           
✓ Pre-processing app...
Added Driver `wj3e`
✓ Typescript detected. Compiling...
✓ Typescript compilation successful
✓ Validating app...
✖ App did not validate against level `debug`:
✖ Error: drivers.wj3e invalid capability: fujitsu_economy
    at App._validate (/usr/local/lib/node_modules/homey/lib/App.js:118:13)
    at async App.runDocker (/usr/local/lib/node_modules/homey/lib/App.js:240:19)
    at async exports.handler (/usr/local/lib/node_modules/homey/bin/cmds/app/run.js:43:5)

**Comment by nextlevel2023** [comment]
Disregard - I worked it out. I am in love with you, this is awesome.

**Comment by mskg** [comment]
You want to check in your changes ;)
Than I love you, too.

**Comment by nextlevel2023** [comment]
You should publish to the store!

**Comment by mskg** [comment]
I have published Apps in the store. This thing doesn't have a big audience and they raised the bar what needs to be delivered to do so. Don't have the time currently.

**Comment by nextlevel2023** [comment]
Fair enough - it works in debug mode locally but as soon as I stop debug mode it uninstalls it from my homey pro.

When I publish during validation it throws errors around the image sizes

✖ App did not validate against level `publish`:
✖ Invalid image size (75x75): /Users/test/Desktop/org.zapto.nextlevel/.homeybuild/assets/images/small.png
Required: 250x175

I have created the correct images sizes for the driver assets dir and the correct sizes for standard assets dir but it still throws this? any ideas? I only want to publish for self use as its awesome.

**Comment by mskg** [comment]
You don't need to - just run 'homey app install' (instead of run). It stays installed.

That's how I do it for my one 'chiller.'

**Comment by mskg** [comment]
I published the App, so you can download it probably later this month.
